name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: docs-${{ github.ref }}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm --filter playground build
        env:
          SITE: https://shravanngoswamii.github.io
          BASE_PATH: /astro-docs
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/playground/dist
